/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./templates/**/*.html", "./static/js/**/*.js"],
  safelist: [
    // Custom color classes
    "bg-lightsteelblue",
    "bg-powderblue",
    "bg-lightblue",
    "bg-skyblue",
    "bg-lightskyblue",
    "bg-steelblue",
    "bg-cornflowerblue",
    "bg-[#AEC6CF]",
    "bg-[#B2F2BB]",
    "bg-[#FFFACD]",
    "bg-[#D7BDE2]",
    "bg-[#F7CAC9]",
    "bg-[#B2DFDB]",
    "bg-[#FFDAB9]",
    // Border colors for custom hex colors
    "border-[#AEC6CF]",
    "border-[#B2F2BB]",
    "border-[#FFFACD]",
    "border-[#D7BDE2]",
    "border-[#F7CAC9]",
    "border-[#B2DFDB]",
    "border-[#FFDAB9]",
    // Text colors for custom hex colors
    "text-[#AEC6CF]",
    "text-[#B2F2BB]",
    "text-[#FFFACD]",
    "text-[#D7BDE2]",
    "text-[#F7CAC9]",
    "text-[#B2DFDB]",
    "text-[#FFDAB9]",
    // Named color borders
    "border-lightsteelblue",
    "border-powderblue",
    "border-lightblue",
    "border-skyblue",
    "border-lightskyblue",
    "border-steelblue",
    "border-cornflowerblue",
    // Named color text
    "text-lightsteelblue",
    "text-powderblue",
    "text-lightblue",
    "text-skyblue",
    "text-lightskyblue",
    "text-steelblue",
    "text-cornflowerblue",
    // Due date status colors
    "bg-red-500",
    "bg-orange-500",
    "bg-yellow-500",
    "bg-yellow-200",
    "text-white",
    "text-yellow-700",
    "text-yellow-800",
    "text-blue-800",
    "text-red-800",
    // Common utility classes that might be used dynamically
    {
      pattern:
        /^bg-(red|blue|green|yellow|orange|gray|neutral)-(100|200|300|400|500|600|700|800|900)$/,
    },
    {
      pattern:
        /^border-(red|blue|green|yellow|orange|gray|neutral)-(100|200|300|400|500|600|700|800|900)$/,
    },
    {
      pattern:
        /^text-(red|blue|green|yellow|orange|gray|neutral)-(100|200|300|400|500|600|700|800|900)$/,
    },
    // Responsive classes that are being purged
    "lg:ml-2",
    "lg:px-2",
    "lg:justify-normal",
    "lg:flex-col",
    "lg:grow",
    "lg:w-48",
    "lg:pt-6",
    "lg:gap-10",
    "lg:h-full",
    "lg:rounded-md",
    "lg:shadow-md",
    "lg:border",
    "lg:px-48",
    "lg:flex-row",
    "lg:bg-neutral-100",
    "lg:w-auto",
    "lg:-top-[22rem]",
    "lg:block",
    "lg:w-[23rem]",
    "lg:border-gray-200",
    "lg:text-left",
    "lg:text-4xl",
    "lg:text-base",
    "lg:w-[*rem]",
    "lg:w-[30rem]",
    "lg:w-[35rem]",
    "lg:w-[40rem]",
    "lg:w-[24rem]",
    "lg:w-60",
    "lg:w-96",
    "lg:w-24",
    "lg:w-12",
    "lg:size-12",
    "lg:size-6",
    "lg:size-5",
    "lg:size-4",
    "lg:text-xl",
    "lg:text-2xl",
    "lg:text-8xl",
    "lg:text-[10rem]",
    "lg:text-sm",
    "lg:text-xs",
    "lg:hidden",
    "lg:flex",
    "lg:grid",
    "lg:grid-cols-3",
    "lg:gap-4",
    "lg:w-full",
    "lg:py-24",
    "lg:py-6",
    "lg:py-1",
    "lg:px-24",
    "lg:my-2",
    "lg:mx-4",
    "lg:ml-0",
    "lg:mr-24",
    "lg:mt-20",
    "lg:mb-36",
    "lg:ml-[12.5rem]",
    "lg:right-auto",
    "lg:bg-neutral-50",
    "min-w-[30rem]",
    "min-w-[40rem]",
    "min-w-[45rem]",
    "min-w-[50rem]",
    "w-52",
    "sticky",
    "lg:sticky",
    "h-full",
    "lg:h-full",
    "top-18",
    "top-20",
    "top-22",
    "top-24",
    // Filter-related classes
    "space-y-2",
    "space-y-6",
    "focus:ring-blue-500",
    "focus:border-blue-500",
    "hover:bg-gray-200",
    "overflow-y-auto",
    "border-b",
    "checked:bg-blue-500",
    "checked:border-blue-500",
    "bg-blue-100",
    "text-blue-800",
    "inline-flex",
    "items-center",
    "rounded-full",
    "font-medium",
    "justify-between",
    "text-blue-600",
    "hover:text-blue-800",
    "underline",
    "h-4",
  ],
  theme: {
    extend: {
      fontFamily: {
        merriweather: ["Merriweather Sans", "sans-serif"],
      },
      colors: {
        "brand-blue": "#3B82F6",
        "brand-gray": "#1F2937",
        lightsteelblue: "#b0c4de",
        powderblue: "#b0e0e6",
        lightblue: "#add8e6",
        skyblue: "#87ceeb",
        lightskyblue: "#87cefa",
        steelblue: "#4682b4",
        cornflowerblue: "#6495ed",
      },
    },
  },
  plugins: [],
};
